/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTenantsListRouteImport } from './routes/_app.tenants.list'
import { Route as AppTasksTemplatesRouteImport } from './routes/_app.tasks.templates'
import { Route as AppTasksListRouteImport } from './routes/_app.tasks.list'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'
import { Route as AppTagsListRouteImport } from './routes/_app.tags.list'
import { Route as AppSystemUsersRouteImport } from './routes/_app.system.users'
import { Route as AppSystemRolesRouteImport } from './routes/_app.system.roles'
import { Route as AppSystemMenusRouteImport } from './routes/_app.system.menus'
import { Route as AppSystemDepartmentsRouteImport } from './routes/_app.system.departments'
import { Route as AppResourcesIpsRouteImport } from './routes/_app.resources.ips'
import { Route as AppResourcesImagesRouteImport } from './routes/_app.resources.images'
import { Route as AppResourcesDevicesRouteImport } from './routes/_app.resources.devices'
import { Route as AppMaterialsPostsRouteImport } from './routes/_app.materials.posts'
import { Route as AppMaterialsAiRouteImport } from './routes/_app.materials.ai'
import { Route as AppAgentsWorkspaceRouteImport } from './routes/_app.agents.workspace'
import { Route as AppAgentsModelsRouteImport } from './routes/_app.agents.models'
import { Route as AppAgentsListRouteImport } from './routes/_app.agents.list'
import { Route as AppAccountsManagedIndexRouteImport } from './routes/_app.accounts.managed.index'
import { Route as AppAccountsManagedIdRouteImport } from './routes/_app.accounts.managed.$id'
import { Route as AppTasksTaskIdLogsIndexRouteImport } from './routes/_app.tasks.$taskId_.logs.index'
import { Route as AppTasksTaskIdLogsLogIdRouteImport } from './routes/_app.tasks.$taskId_.logs.$logId'
import { Route as AppTasksTaskIdLogsSubSubIdRouteImport } from './routes/_app.tasks.$taskId_.logs.sub.$subId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsListRoute = AppTenantsListRouteImport.update({
  id: '/tenants/list',
  path: '/tenants/list',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTemplatesRoute = AppTasksTemplatesRouteImport.update({
  id: '/tasks/templates',
  path: '/tasks/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksListRoute = AppTasksListRouteImport.update({
  id: '/tasks/list',
  path: '/tasks/list',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsListRoute = AppTagsListRouteImport.update({
  id: '/tags/list',
  path: '/tags/list',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemUsersRoute = AppSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRolesRoute = AppSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemMenusRoute = AppSystemMenusRouteImport.update({
  id: '/system/menus',
  path: '/system/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemDepartmentsRoute = AppSystemDepartmentsRouteImport.update({
  id: '/system/departments',
  path: '/system/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIpsRoute = AppResourcesIpsRouteImport.update({
  id: '/resources/ips',
  path: '/resources/ips',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesImagesRoute = AppResourcesImagesRouteImport.update({
  id: '/resources/images',
  path: '/resources/images',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesDevicesRoute = AppResourcesDevicesRouteImport.update({
  id: '/resources/devices',
  path: '/resources/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsPostsRoute = AppMaterialsPostsRouteImport.update({
  id: '/materials/posts',
  path: '/materials/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsAiRoute = AppMaterialsAiRouteImport.update({
  id: '/materials/ai',
  path: '/materials/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsWorkspaceRoute = AppAgentsWorkspaceRouteImport.update({
  id: '/agents/workspace',
  path: '/agents/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsModelsRoute = AppAgentsModelsRouteImport.update({
  id: '/agents/models',
  path: '/agents/models',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsListRoute = AppAgentsListRouteImport.update({
  id: '/agents/list',
  path: '/agents/list',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsManagedIndexRoute = AppAccountsManagedIndexRouteImport.update({
  id: '/accounts/managed/',
  path: '/accounts/managed/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsManagedIdRoute = AppAccountsManagedIdRouteImport.update({
  id: '/accounts/managed/$id',
  path: '/accounts/managed/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdLogsIndexRoute = AppTasksTaskIdLogsIndexRouteImport.update({
  id: '/tasks/$taskId_/logs/',
  path: '/tasks/$taskId/logs/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdLogsLogIdRoute = AppTasksTaskIdLogsLogIdRouteImport.update({
  id: '/tasks/$taskId_/logs/$logId',
  path: '/tasks/$taskId/logs/$logId',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdLogsSubSubIdRoute =
  AppTasksTaskIdLogsSubSubIdRouteImport.update({
    id: '/tasks/$taskId_/logs/sub/$subId',
    path: '/tasks/$taskId/logs/sub/$subId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agents/list': typeof AppAgentsListRoute
  '/agents/models': typeof AppAgentsModelsRoute
  '/agents/workspace': typeof AppAgentsWorkspaceRoute
  '/materials/ai': typeof AppMaterialsAiRoute
  '/materials/posts': typeof AppMaterialsPostsRoute
  '/resources/devices': typeof AppResourcesDevicesRoute
  '/resources/images': typeof AppResourcesImagesRoute
  '/resources/ips': typeof AppResourcesIpsRoute
  '/system/departments': typeof AppSystemDepartmentsRoute
  '/system/menus': typeof AppSystemMenusRoute
  '/system/roles': typeof AppSystemRolesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/tags/list': typeof AppTagsListRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/templates': typeof AppTasksTemplatesRoute
  '/tenants/list': typeof AppTenantsListRoute
  '/accounts/managed/$id': typeof AppAccountsManagedIdRoute
  '/accounts/managed/': typeof AppAccountsManagedIndexRoute
  '/tasks/$taskId/logs/$logId': typeof AppTasksTaskIdLogsLogIdRoute
  '/tasks/$taskId/logs/': typeof AppTasksTaskIdLogsIndexRoute
  '/tasks/$taskId/logs/sub/$subId': typeof AppTasksTaskIdLogsSubSubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/agents/list': typeof AppAgentsListRoute
  '/agents/models': typeof AppAgentsModelsRoute
  '/agents/workspace': typeof AppAgentsWorkspaceRoute
  '/materials/ai': typeof AppMaterialsAiRoute
  '/materials/posts': typeof AppMaterialsPostsRoute
  '/resources/devices': typeof AppResourcesDevicesRoute
  '/resources/images': typeof AppResourcesImagesRoute
  '/resources/ips': typeof AppResourcesIpsRoute
  '/system/departments': typeof AppSystemDepartmentsRoute
  '/system/menus': typeof AppSystemMenusRoute
  '/system/roles': typeof AppSystemRolesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/tags/list': typeof AppTagsListRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/templates': typeof AppTasksTemplatesRoute
  '/tenants/list': typeof AppTenantsListRoute
  '/accounts/managed/$id': typeof AppAccountsManagedIdRoute
  '/accounts/managed': typeof AppAccountsManagedIndexRoute
  '/tasks/$taskId/logs/$logId': typeof AppTasksTaskIdLogsLogIdRoute
  '/tasks/$taskId/logs': typeof AppTasksTaskIdLogsIndexRoute
  '/tasks/$taskId/logs/sub/$subId': typeof AppTasksTaskIdLogsSubSubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/agents/list': typeof AppAgentsListRoute
  '/_app/agents/models': typeof AppAgentsModelsRoute
  '/_app/agents/workspace': typeof AppAgentsWorkspaceRoute
  '/_app/materials/ai': typeof AppMaterialsAiRoute
  '/_app/materials/posts': typeof AppMaterialsPostsRoute
  '/_app/resources/devices': typeof AppResourcesDevicesRoute
  '/_app/resources/images': typeof AppResourcesImagesRoute
  '/_app/resources/ips': typeof AppResourcesIpsRoute
  '/_app/system/departments': typeof AppSystemDepartmentsRoute
  '/_app/system/menus': typeof AppSystemMenusRoute
  '/_app/system/roles': typeof AppSystemRolesRoute
  '/_app/system/users': typeof AppSystemUsersRoute
  '/_app/tags/list': typeof AppTagsListRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/tasks/list': typeof AppTasksListRoute
  '/_app/tasks/templates': typeof AppTasksTemplatesRoute
  '/_app/tenants/list': typeof AppTenantsListRoute
  '/_app/accounts/managed/$id': typeof AppAccountsManagedIdRoute
  '/_app/accounts/managed/': typeof AppAccountsManagedIndexRoute
  '/_app/tasks/$taskId_/logs/$logId': typeof AppTasksTaskIdLogsLogIdRoute
  '/_app/tasks/$taskId_/logs/': typeof AppTasksTaskIdLogsIndexRoute
  '/_app/tasks/$taskId_/logs/sub/$subId': typeof AppTasksTaskIdLogsSubSubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/list'
    | '/agents/models'
    | '/agents/workspace'
    | '/materials/ai'
    | '/materials/posts'
    | '/resources/devices'
    | '/resources/images'
    | '/resources/ips'
    | '/system/departments'
    | '/system/menus'
    | '/system/roles'
    | '/system/users'
    | '/tags/list'
    | '/tasks/$taskId'
    | '/tasks/list'
    | '/tasks/templates'
    | '/tenants/list'
    | '/accounts/managed/$id'
    | '/accounts/managed/'
    | '/tasks/$taskId/logs/$logId'
    | '/tasks/$taskId/logs/'
    | '/tasks/$taskId/logs/sub/$subId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/list'
    | '/agents/models'
    | '/agents/workspace'
    | '/materials/ai'
    | '/materials/posts'
    | '/resources/devices'
    | '/resources/images'
    | '/resources/ips'
    | '/system/departments'
    | '/system/menus'
    | '/system/roles'
    | '/system/users'
    | '/tags/list'
    | '/tasks/$taskId'
    | '/tasks/list'
    | '/tasks/templates'
    | '/tenants/list'
    | '/accounts/managed/$id'
    | '/accounts/managed'
    | '/tasks/$taskId/logs/$logId'
    | '/tasks/$taskId/logs'
    | '/tasks/$taskId/logs/sub/$subId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/agents/list'
    | '/_app/agents/models'
    | '/_app/agents/workspace'
    | '/_app/materials/ai'
    | '/_app/materials/posts'
    | '/_app/resources/devices'
    | '/_app/resources/images'
    | '/_app/resources/ips'
    | '/_app/system/departments'
    | '/_app/system/menus'
    | '/_app/system/roles'
    | '/_app/system/users'
    | '/_app/tags/list'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/list'
    | '/_app/tasks/templates'
    | '/_app/tenants/list'
    | '/_app/accounts/managed/$id'
    | '/_app/accounts/managed/'
    | '/_app/tasks/$taskId_/logs/$logId'
    | '/_app/tasks/$taskId_/logs/'
    | '/_app/tasks/$taskId_/logs/sub/$subId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/list': {
      id: '/_app/tenants/list'
      path: '/tenants/list'
      fullPath: '/tenants/list'
      preLoaderRoute: typeof AppTenantsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/templates': {
      id: '/_app/tasks/templates'
      path: '/tasks/templates'
      fullPath: '/tasks/templates'
      preLoaderRoute: typeof AppTasksTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/list': {
      id: '/_app/tasks/list'
      path: '/tasks/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AppTasksListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags/list': {
      id: '/_app/tags/list'
      path: '/tags/list'
      fullPath: '/tags/list'
      preLoaderRoute: typeof AppTagsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/users': {
      id: '/_app/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AppSystemUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/roles': {
      id: '/_app/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof AppSystemRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/menus': {
      id: '/_app/system/menus'
      path: '/system/menus'
      fullPath: '/system/menus'
      preLoaderRoute: typeof AppSystemMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/departments': {
      id: '/_app/system/departments'
      path: '/system/departments'
      fullPath: '/system/departments'
      preLoaderRoute: typeof AppSystemDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/ips': {
      id: '/_app/resources/ips'
      path: '/resources/ips'
      fullPath: '/resources/ips'
      preLoaderRoute: typeof AppResourcesIpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/images': {
      id: '/_app/resources/images'
      path: '/resources/images'
      fullPath: '/resources/images'
      preLoaderRoute: typeof AppResourcesImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/devices': {
      id: '/_app/resources/devices'
      path: '/resources/devices'
      fullPath: '/resources/devices'
      preLoaderRoute: typeof AppResourcesDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/posts': {
      id: '/_app/materials/posts'
      path: '/materials/posts'
      fullPath: '/materials/posts'
      preLoaderRoute: typeof AppMaterialsPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/ai': {
      id: '/_app/materials/ai'
      path: '/materials/ai'
      fullPath: '/materials/ai'
      preLoaderRoute: typeof AppMaterialsAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/workspace': {
      id: '/_app/agents/workspace'
      path: '/agents/workspace'
      fullPath: '/agents/workspace'
      preLoaderRoute: typeof AppAgentsWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/models': {
      id: '/_app/agents/models'
      path: '/agents/models'
      fullPath: '/agents/models'
      preLoaderRoute: typeof AppAgentsModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/list': {
      id: '/_app/agents/list'
      path: '/agents/list'
      fullPath: '/agents/list'
      preLoaderRoute: typeof AppAgentsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/managed/': {
      id: '/_app/accounts/managed/'
      path: '/accounts/managed'
      fullPath: '/accounts/managed/'
      preLoaderRoute: typeof AppAccountsManagedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/managed/$id': {
      id: '/_app/accounts/managed/$id'
      path: '/accounts/managed/$id'
      fullPath: '/accounts/managed/$id'
      preLoaderRoute: typeof AppAccountsManagedIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId_/logs/': {
      id: '/_app/tasks/$taskId_/logs/'
      path: '/tasks/$taskId/logs'
      fullPath: '/tasks/$taskId/logs/'
      preLoaderRoute: typeof AppTasksTaskIdLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId_/logs/$logId': {
      id: '/_app/tasks/$taskId_/logs/$logId'
      path: '/tasks/$taskId/logs/$logId'
      fullPath: '/tasks/$taskId/logs/$logId'
      preLoaderRoute: typeof AppTasksTaskIdLogsLogIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId_/logs/sub/$subId': {
      id: '/_app/tasks/$taskId_/logs/sub/$subId'
      path: '/tasks/$taskId/logs/sub/$subId'
      fullPath: '/tasks/$taskId/logs/sub/$subId'
      preLoaderRoute: typeof AppTasksTaskIdLogsSubSubIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsListRoute: typeof AppAgentsListRoute
  AppAgentsModelsRoute: typeof AppAgentsModelsRoute
  AppAgentsWorkspaceRoute: typeof AppAgentsWorkspaceRoute
  AppMaterialsAiRoute: typeof AppMaterialsAiRoute
  AppMaterialsPostsRoute: typeof AppMaterialsPostsRoute
  AppResourcesDevicesRoute: typeof AppResourcesDevicesRoute
  AppResourcesImagesRoute: typeof AppResourcesImagesRoute
  AppResourcesIpsRoute: typeof AppResourcesIpsRoute
  AppSystemDepartmentsRoute: typeof AppSystemDepartmentsRoute
  AppSystemMenusRoute: typeof AppSystemMenusRoute
  AppSystemRolesRoute: typeof AppSystemRolesRoute
  AppSystemUsersRoute: typeof AppSystemUsersRoute
  AppTagsListRoute: typeof AppTagsListRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksListRoute: typeof AppTasksListRoute
  AppTasksTemplatesRoute: typeof AppTasksTemplatesRoute
  AppTenantsListRoute: typeof AppTenantsListRoute
  AppAccountsManagedIdRoute: typeof AppAccountsManagedIdRoute
  AppAccountsManagedIndexRoute: typeof AppAccountsManagedIndexRoute
  AppTasksTaskIdLogsLogIdRoute: typeof AppTasksTaskIdLogsLogIdRoute
  AppTasksTaskIdLogsIndexRoute: typeof AppTasksTaskIdLogsIndexRoute
  AppTasksTaskIdLogsSubSubIdRoute: typeof AppTasksTaskIdLogsSubSubIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAgentsListRoute: AppAgentsListRoute,
  AppAgentsModelsRoute: AppAgentsModelsRoute,
  AppAgentsWorkspaceRoute: AppAgentsWorkspaceRoute,
  AppMaterialsAiRoute: AppMaterialsAiRoute,
  AppMaterialsPostsRoute: AppMaterialsPostsRoute,
  AppResourcesDevicesRoute: AppResourcesDevicesRoute,
  AppResourcesImagesRoute: AppResourcesImagesRoute,
  AppResourcesIpsRoute: AppResourcesIpsRoute,
  AppSystemDepartmentsRoute: AppSystemDepartmentsRoute,
  AppSystemMenusRoute: AppSystemMenusRoute,
  AppSystemRolesRoute: AppSystemRolesRoute,
  AppSystemUsersRoute: AppSystemUsersRoute,
  AppTagsListRoute: AppTagsListRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksListRoute: AppTasksListRoute,
  AppTasksTemplatesRoute: AppTasksTemplatesRoute,
  AppTenantsListRoute: AppTenantsListRoute,
  AppAccountsManagedIdRoute: AppAccountsManagedIdRoute,
  AppAccountsManagedIndexRoute: AppAccountsManagedIndexRoute,
  AppTasksTaskIdLogsLogIdRoute: AppTasksTaskIdLogsLogIdRoute,
  AppTasksTaskIdLogsIndexRoute: AppTasksTaskIdLogsIndexRoute,
  AppTasksTaskIdLogsSubSubIdRoute: AppTasksTaskIdLogsSubSubIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
